---
version: 2
updates:
  - package-ecosystem: uv
    directory: /
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
