# Generated by Django 5.2.12 on 2026-04-10 05:42

from django.db import migrations, models
from django.apps.registry import Apps
from django.db.models import F
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

def populate_dhcp_urls( apps: Apps, schema_editor: BaseDatabaseSchemaEditor ) -> None:
    Server = apps.get_model("netbox_kea", "Server")
    db_alias = schema_editor.connection.alias
    Server.objects.using(db_alias).filter(dhcp4=True).update(dhcp4_url=F("server_url"))
    Server.objects.using(db_alias).filter(dhcp6=True).update(dhcp6_url=F("server_url"))

def remove_dhcp_urls( apps: Apps, schema_editor: BaseDatabaseSchemaEditor ) -> None:
    Server = apps.get_model("netbox_kea", "Server")
    db_alias = schema_editor.connection.alias
    Server.objects.using(db_alias).filter(dhcp4_url__null=False).update(server_url=F("dhcp4_url"), dhcp4=True)
    Server.objects.using(db_alias).filter(dhcp6_url__null=False).update(server_url=F("dhcp6_url"),dhcp6=True)

class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0002_alter_server_options_server_dhcp4_server_dhcp6'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dhcp4_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='dhcp6_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_dhcp_urls, remove_dhcp_urls),
        migrations.RemoveField(
            model_name='server',
            name='dhcp4',
        ),
        migrations.RemoveField(
            model_name='server',
            name='dhcp6',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_url',
        ),
    ]
