---
name: CI

"on":
  push:
    branches:
      - "*"
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - run: poetry install
        if: steps.setup-python.outputs.cache-hit != 'true'

      - uses: psf/black@stable

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --max-line-length=120 --show-source --statistics
  test:
    strategy:
      matrix:
        include:
          - netbox: v3.5
          - netbox: v3.6
          - netbox: v3.7

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - run: poetry install
        if: steps.setup-python.outputs.cache-hit != 'true'

      - name: Ensure playwright browsers are installed
        run: poetry run playwright install --with-deps

      - name: Run poetry build
        run: poetry build

      - name: Run test_setup.sh
        run: ./tests/test_setup.sh
        env:
          NETBOX_CONTAINER_TAG: ${{ matrix.netbox }}

      - name: Run pytest
        run: |
          poetry run pytest -v

      - name: Show Docker logs
        if: ${{ always() }}
        run: docker-compose logs
        working-directory: ./tests/docker/
